apiVersion: v1
kind: LimitRange
metadata:
  name: jenkins
  namespace: jenkins
spec:
  limits:
  - default:
      cpu: 4.0
      memory: 4Gi
    defaultRequest:
      cpu: 2.0
      memory: 2Gi
    type: Container
  