apiVersion: v1
kind: Service
metadata:
  labels:
    run: jenkins
  name: jenkins
  namespace: jenkins
spec:
  ports:
  - port: 8080
    protocol: TCP
#    targetPort: 8080
  selector:
    run: jenkins
  sessionAffinity: None
  type: LoadBalancer
