apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-dev-deplpoyment
  namespace: jenkins
  labels:
    app: jenkins-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-dev
  template:
    metadata:
      name: jenkins-dev-replicaset
      labels:
        app: jenkins-dev
    spec:
      containers:
        - name: jenkins-dev-pod
          image: pdaambrosio/jenkinslab:2.5.1
          ports:
          -  name: http-port
             containerPort: 8080
          -  name: jnlp-port
             containerPort: 50000
          resources:
            requests:
              memory: "512Mi"
              cpu: "1.0"
            limits:
              memory: "3Gi"
              cpu: "2.0"
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-dev-service
  namespace: jenkins
  labels:
    app: jenkins-dev
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: jenkins-dev
