apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: votingapp
  labels:
    app: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - image: kodekloud/examplevotingapp_result:v1
          name: result
          ports:
            - containerPort: 80
          env:
            - name: REDIS
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"