apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
  namespace: votingapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - image: kodekloud/examplevotingapp_worker:v1
          name: worker
          ports:
            - containerPort: 80
              name: http
          env:
            - name: REDIS
              value: redis
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          resources:
            requests:
              memory: "256Mi"
              cpu: "512m"
            limits:
              memory: "512Mi"
              cpu: "1.0"
