apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: votingapp
  labels:
    app: result
spec:
  ports:
  - port: 5001
    targetPort: 80
    nodePort: 31001
  selector:
    app: result
  type: NodePort
